#ifndef _DT_BINDINGS_CLOCK_EXYNOS3475_H
#define _DT_BINDINGS_CLOCK_EXYNOS3475_H

/*			BUS0			*/
#define BUS0_NR_CLK   						1

/*			BUS2			*/
#define BUS2_NR_CLK    					1

/*			CPU			*/
#define CLK_MOUT_CPU						1
#define CLK_CPU_PLL						2

#define CPU_NR_CLK						3

/*			DISPAUD			*/
#define CLK_MOUT_SCLK_DECON_INT_VCLK_USER			1
#define CLK_MOUT_SCLK_DECON_INT_ECLK_USER			2
#define CLK_MOUT_SCLK_MI2S_AUD_USER				3
#define CLK_DOUT_SCLK_DECON_INT_VCLK				4
#define CLK_DOUT_SCLK_DECON_INT_ECLK				5
#define CLK_DOUT_SCLK_MI2S_AUD					6
#define CLK_DOUT_SCLK_MIXER_AUD					7
#define CLK_ACLK_DISPAUD_133_PCLK_DISPAUD_P			8
#define CLK_ACLK_DISPAUD_133_ACLK_AUD				9
#define CLK_ACLK_DISPAUD_133_ACLK_DISP				10
#define CLK_ACLK_DISPAUD_133_ACLK_DISPAUD_D			11
#define CLK_SCLK_DISP_DECON_INT_VCLK				12
#define CLK_SCLK_DISP_DECON_INT_ECLK				13
#define CLK_PHYCLK_MIPI_PHY_M_TXBYTECLKHS_M4S4_PHYCLK_DSI_LINK0_BITCLKDIV8	14
#define CLK_PHYCLK_MIPI_PHY_M_RXCLKESC0_M4S4_PHYCLK_DSI_LINK0_RXCLKESC0		15
#define CLK_SCLK_MI2S_AUD_SCLK_MI2S_I2SCODCLKI			16
#define CLK_SCLK_MIXER_AUD_SYSCLK				17
#define CLK_IOCLK_AUD_I2S_SCLK_AP_IN_SCLK_MI2S_AUD_SCLK_AP_IN	18
#define CLK_IOCLK_AUD_I2S_BCLK_BT_IN_SCLK_MI2S_AUD_BCLK_BT_IN	19
#define CLK_IOCLK_AUD_I2S_BCLK_CP_IN_SCLK_MI2S_AUD_BCLK_CP_IN	20
#define CLK_IOCLK_AUD_I2S_BCLK_FM_IN_SCLK_MI2S_AUD_BCLK_FM_IN	21
#define CLK_MOUT_SCLK_MI2S_AUD					22
#define CLK_MOUT_ACLK_DISPAUD_133_USER				23

#define DISPAUD_NR_CLK						24

/*			FSYS			*/
#define CLK_ACLK_FSYS_200_ACLK_UPSIZER_AHB_USBHS_ACLK		1
#define CLK_ACLK_FSYS_200_ACLK_UPSIZER_FSYS1_TO_FSYS0_ACLK	2
#define CLK_ACLK_FSYS_200_ACLK_AHB2AXI_USBHS_HCLK		3
#define CLK_ACLK_FSYS_200_ACLK_AHB_USBHS_HCLK			4
#define CLK_ACLK_FSYS_200_ACLK_XIU_D_FSYS1_ACLK			5
#define CLK_ACLK_FSYS_200_ACLK_UPSIZER_USBOTG_ACLK		6
#define CLK_ACLK_FSYS_200_ACLK_AHB2AXI_USBOTG_HCLK		7
#define CLK_ACLK_FSYS_200_ACLK_USBOTG20_ACLK			8
#define CLK_ACLK_FSYS_200_ACLK_MMC2_I_ACLK			9
#define CLK_ACLK_FSYS_200_ACLK_MMC1_I_ACLK			10
#define CLK_ACLK_FSYS_200_ACLK_MMC0_I_ACLK			11
#define CLK_ACLK_FSYS_200_ACLK_USBHOST20_ACLK			12
#define CLK_ACLK_FSYS_200_ACLK_DMA_FSYS1_ACLK			13
#define CLK_ACLK_FSYS_200_ACLK_DMA_FSYS0_ACLK			14
#define CLK_SCLK_FSYS_MMC0_SDCLKIN_SCLK_MMC0_SDCLKIN		15
#define CLK_SCLK_FSYS_MMC1_SDCLKIN_SCLK_MMC1_SDCLKIN		16
#define CLK_SCLK_FSYS_MMC2_SDCLKIN_SCLK_MMC2_SDCLKIN		17
#define CLK_USB_PLL						18
#define CLK_PHYCLK_USBHOST20_USB20_FREECLK			19
#define CLK_PHYCLK_USBHOST20_USB20_PHYCLOCK			20
#define CLK_PHYCLK_USBHOST20_USB20_CLK48MOHCI			21
#define CLK_MOUT_SCLK_FSYS_MMC0_SDCLKIN_USER			22
#define CLK_MOUT_SCLK_FSYS_MMC1_SDCLKIN_USER			23
#define CLK_MOUT_SCLK_FSYS_MMC2_SDCLKIN_USER			24
#define CLK_MOUT_PHYCLK_USBOTG_OTG20_PHYCLOCK_USER		25

#define FSYS_NR_CLK						26

/*			G3D			*/
#define CLK_MOUT_ACLK_G3D_667					1
#define CLK_ACLK_G3D_667_ACLK_G3D_CLK				2

#define G3D_NR_CLK						3	

/*			PERIC			*/
#define CLK_ACLK_PERI_PCLK_HSI2C8_IPCLK				1
#define CLK_ACLK_PERI_PCLK_HSI2C7_IPCLK				2
#define CLK_ACLK_PERI_PCLK_HSI2C1_IPCLK				3
#define CLK_ACLK_PERI_PCLK_HSI2C0_IPCLK				4
#define CLK_ACLK_PERI_PCLK_I2C6_PCLK				5
#define CLK_ACLK_PERI_PCLK_I2C5_PCLK				6
#define CLK_ACLK_PERI_PCLK_I2C4_PCLK				7
#define CLK_ACLK_PERI_PCLK_I2C3_PCLK				8
#define CLK_ACLK_PERI_PCLK_WDT_CPU_PCLK				9
#define CLK_ACLK_PERI_PCLK_MCT_PCLK				10
#define CLK_ACLK_PERI_SECURE_RTC_PCLK_RTC_APBIF_PCLK		11
#define CLK_ACLK_PERI_PCLK_PWM_PCLK				12
#define CLK_ACLK_PERI_PCLK_I2C10_PCLK				13
#define CLK_ACLK_PERI_PCLK_I2C9_PCLK				14
#define CLK_ACLK_PERI_PCLK_SPI2_PCLK				15
#define CLK_ACLK_PERI_PCLK_SPI1_PCLK				16
#define CLK_ACLK_PERI_PCLK_SPI0_PCLK				17
#define CLK_ACLK_PERI_PCLK_ADCIF_PCLK				18
#define CLK_ACLK_PERI_PCLK_UART2_PCLK				19
#define CLK_ACLK_PERI_PCLK_UART1_PCLK				20
#define CLK_ACLK_PERI_PCLK_UART0_PCLK				21
#define CLK_SCLK_PERI_SPI0_SPI_EXT_CLK_SCLK_SPI0_SPI_EXT_CLK	22
#define CLK_SCLK_PERI_SPI1_SPI_EXT_CLK_SCLK_SPI1_SPI_EXT_CLK	23
#define CLK_SCLK_PERI_SPI2_SPI_EXT_CLK_SCLK_SPI2_SPI_EXT_CLK	24
#define CLK_SCLK_PERI_UART0_EXT_UCLK_SCLK_UART0_EXT_UCLK	25
#define CLK_SCLK_PERI_UART1_EXT_UCLK_SCLK_UART1_EXT_UCLK	26
#define CLK_SCLK_PERI_UART2_EXT_UCLK_SCLK_UART2_EXT_UCLK	27

#define PERI_NR_CLK						28

/*			MIF			*/
#define CLK_MEM0_PLL						1
#define CLK_BUS_PLL						2

#define CLK_MOUT_ACLK_MIF_333					3
#define CLK_MOUT_ACLK_MIF_83					4
#define CLK_MOUT_ACLK_MIF_FIX_50				5
#define CLK_MOUT_ACLK_DISPAUD_133				6
#define CLK_MOUT_ACLK_ISP_300					7
#define CLK_MOUT_SCLK_DISP_DECON_INT_ECLK			8
#define CLK_MOUT_SCLK_DISP_DECON_INT_VCLK			9

#define CLK_DOUT_ACLK_MIF_333					10
#define CLK_DOUT_ACLK_MIF_166					11
#define CLK_DOUT_ACLK_MIF_83					12
#define CLK_DOUT_ACLK_MIF_FIX_50				13
#define CLK_DOUT_ACLK_DISPAUD_133				14
#define CLK_DOUT_ACLK_ISP_300					15
#define CLK_DOUT_SCLK_DISP_DECON_INT_ECLK			16
#define CLK_DOUT_SCLK_DISP_DECON_INT_VCLK			17
#define CLK_DOUT_MIF_NODDR					18

#define CLK_ACLK_MIF_FIX_50_PCLK_MASYNC_HSI2C_CP_PCLK		19
#define CLK_ACLK_MIF_FIX_50_PCLK_MASYNC_HSI2C_AP_PCLK		20
#define CLK_ACLK_MIF_FIX_50_PCLK_HSI2C_MIF_PCLK			21
#define CLK_ACLK_CPU_800					22
#define CLK_SCLK_MEDIA_PLL_TOP					23
#define CLK_SCLK_BUS_PLL_TOP					24

#define MIF_NR_CLK						25

/*			TOP			*/
#define CLK_MOUT_ACLK_BUS0_333					1
#define CLK_MOUT_ACLK_BUS2_333					2
#define CLK_MOUT_ACLK_MFCMSCL_200				3
#define CLK_MOUT_ACLK_MFCMSCL_333				4
#define CLK_MOUT_SCLK_FSYS_MMC0_SDCLKIN				5
#define CLK_MOUT_SCLK_FSYS_MMC1_SDCLKIN				6
#define CLK_MOUT_SCLK_FSYS_MMC2_SDCLKIN				7
#define CLK_MOUT_SCLK_ISP_SENSOR0				8
#define CLK_MOUT_SCLK_ISP_SENSOR1				9

#define CLK_DOUT_ACLK_FSYS_200					10
#define CLK_DOUT_ACLK_IMEM_266					11
#define CLK_DOUT_ACLK_IMEM_200					12
#define CLK_DOUT_ACLK_BUS0_333					13
#define CLK_DOUT_ACLK_BUS2_333					14
#define CLK_DOUT_ACLK_PERI_66					15
#define CLK_DOUT_ACLK_G3D_400					16
#define CLK_DOUT_ACLK_MFCMSCL_200				17
#define CLK_DOUT_ACLK_MFCMSCL_333				18
#define CLK_DOUT_SCLK_FSYS_MMC0_SDCLKIN_A			19
#define CLK_DOUT_SCLK_FSYS_MMC0_SDCLKIN_B			20
#define CLK_DOUT_SCLK_FSYS_MMC1_SDCLKIN_A			21
#define CLK_DOUT_SCLK_FSYS_MMC1_SDCLKIN_B			22
#define CLK_DOUT_SCLK_FSYS_MMC2_SDCLKIN_A			23
#define CLK_DOUT_SCLK_FSYS_MMC2_SDCLKIN_B			24
#define CLK_DOUT_SCLK_PERI_UART0				25
#define CLK_DOUT_SCLK_PERI_UART1				26
#define CLK_DOUT_SCLK_PERI_UART2				27
#define CLK_DOUT_SCLK_ISP_SENSOR0_A				28
#define CLK_DOUT_SCLK_ISP_SENSOR0_B				29
#define CLK_DOUT_SCLK_ISP_SENSOR1_A				30
#define CLK_DOUT_SCLK_ISP_SENSOR1_B				31

#define CLK_ACLK_BUS0_333					32
#define CLK_ACLK_BUS2_333					33
#define CLK_ACLK_PERI_66					34
#define CLK_ACLK_G3D_400					35
#define CLK_SCLK_FSYS_MMC0_SDCLKIN				36
#define CLK_SCLK_FSYS_MMC1_SDCLKIN				37
#define CLK_SCLK_FSYS_MMC2_SDCLKIN				38
#define CLK_SCLK_ISP_SENSOR0					39
#define CLK_SCLK_ISP_SENSOR1					40
#define CLK_MOUT_BUS_PLL_USER					41
#define CLK_MOUT_MEDIA_PLL_USER					42

#define TOP_NR_CLK						43

#endif /* _DT_BINDINGS_CLOCK_EXYNOS3475_H */
